name: examples

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps: 
      - name: Install WasmEdge
        run: curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s
      - name: Install Rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
      - name: Install Rust target
        run: cargo install cargo-wasi
      - name: Checkout code
        uses: actions/checkout@v2
      - name: setup mysql
        uses: mirromutth/mysql-action@v1.1
        with:
          character set server: 'utf8' 
          collation server: 'utf8_general_ci' 
          mysql database: 'db_name' 
          mysql root password: 'password'
      - name: Build & Run
        run: |
          cargo wasi build --example demo
          wasmedge target/wasm32-wasi/debug/examples/demo.wasm